myblog/accounts/urls.py
from django.urls import path
from. import views
app_name='accounts'
urlpatterns=[
path('signup',views.signup,name='signup'),
path('login',views.login_view,name='login'),
path('logout',views.logout_view,name='logout'),
]

myblog/articles/urls.py
from django.urls import path
from django.urls import path, re_path
app_name='articles'
from.import views
urlpatterns = [
    path('',views.article_list ,name='list'),
    path('create',views.article_create,name='create'),
    re_path('^(?P<slug>[\w-]+)/$',views.article_details,name='details'),
]

myblog/feedback/urls.py
from django.urls import path,re_path
app_name='feedback'
from.import views
urlpatterns=[
path('',views.feed,name='feed'),
path('thanks/',views.thanks,name='thanks'),
path('about/',views.about,name='about'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from.import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('feedback/',include('feedback.urls')),
    path('articles/',include('articles.urls')),
    path('about/',views.about),
    path('',article_views.article_list,name='home')
]
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myblog/accounts/models.py
from django.db import models

# Create your models here.

myblog/articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Articles(models.Model):
    title=models.CharField(max_length=20)
    slug=models.SlugField()
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    thumb=models.ImageField(default='default.jpg',blank=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE,default=None)

    def __str__(self):
        return self.title
    def snippat(self):
        return self.body[:50]+"..."

myblog/feedback/models.py
from django.db import models

# Create your models here.
class FeedBack(models.Model):
	feed_back=models.TextField(max_length=200)

	def __str__(self):
		return self.feed_back

class Text(models.Model):
	name=models.CharField(max_length=100)
	email=models.EmailField()
	mob_no=models.CharField(max_length=10)
	query=models.TextField()

	def __str__(self):
		return self.name

myblog/articles/forms.py
from django import forms
from.import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model= models.Articles
        fields=['title','slug','body','thumb']

myblog/feedback/forms.py
from django import forms
from.import models
class GiveFeedback(forms.ModelForm):
	class Meta:
		model=models.FeedBack
		fields=['feed_back']
class TextMe(forms.ModelForm):
	class Meta:
		model=models.Text
		fields=['name','email','mob_no','query']

myblog/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
# Create your views here.
def signup(request):
    if request.method=='POST':
        form=UserCreationForm(request.POST)
        if(form.is_valid()):
            user=form.save()
            login(request,user)

            return redirect('articles:list')
    else:
        form=UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            if('next' in request.POST):
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')

    else:
        form=AuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})
def logout_view(request):
    if(request.method=='POST'):
        logout(request)
        return redirect('articles:list')

myblog/articles/views.py
from django.shortcuts import render,redirect
from.models import Articles
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from.import forms


# Create your views here.
def article_list(request):
    articles=Articles.objects.all().order_by('date')
    return render(request,"articles/article_list.html",{'articles':articles})
def article_details(request,slug):
    #return HttpResponse(slug)
    article=Articles.objects.get(slug=slug)
    return render(request,'articles/details.html',{'article':article})
@login_required(login_url='/accounts/login')
def article_create(request):
    if(request.method=='POST'):
        form=forms.CreateArticle(request.POST,request.FILES)
        if(form.is_valid):
            instance=form.save(commit=False)
            instance.author=request.user
            instance.save()
            return redirect('articles:list')
    else:
        form=forms.CreateArticle()
    return render(request,'articles/article_create.html',{'form':form})

myblog/feedback/views.py
from django.shortcuts import render,redirect
from.import forms
from.models import FeedBack,Text


# Create your views here.
def thanks(request,):
	data=FeedBack.objects.all()

	return render(request,'feedback/thanks.html',{'data':data})
def about(request):
	if(request.method=="POST"):
		form=forms.TextMe(request.POST,request.FILES)
		if(form.is_valid):
			form.save()
			return redirect('feedback:about')
	else:
		form=forms.TextMe()
	return render(request,'feedback/about.html',{'form':form})

	



def feed(request):
	if(request.method=='POST'):
		form=forms.GiveFeedback(request.POST,request.FILES)
		if(form.is_valid):
			form.save()
			return redirect('feedback:thanks')

	else:
		form=forms.GiveFeedback()
	return render(request,'feedback/feed.html',{'form':form})

myblog/myblog/views.py
from django.http import HttpResponse
from django.shortcuts import render
def homepage(request):
    return render(request,"homepage.html")
def about(request):
    return render(request,"about.html")

myblog/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login'%}" method="post">
{% csrf_token %}
  {{form}}
  {% if request.GET.next %}
  <input type="hidden" name="next" value="{{request.GET.next}}">
  {% endif %}
  <input type="submit"  value="Login">
</form>
{% endblock %}

myblog/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>signup</h1>
<form class="site-form" action="/accounts/signup" method="post">
  {% csrf_token %}
  {{form}}
  <input type="submit"  value="Signup">
</form>
{% endblock %}

myblog/articles/templates/articles/article_create.html
{% extends 'base_layout.html'%}
{% block content %}
<div class="create-article">
  <h1>Create Awesome Articles</h1>
  <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
    {{form}}
    <input type="submit"  value="Create">
  </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock%}

myblog/articles/templates/articles/article_list.html
{% extends 'base_layout.html'%}
{% block content%}
<h1>Article list</h1>
    <div class="articles">
      {% for article in articles %}
      <div class="article">
        <h2><a href="{% url 'articles:details' slug=article.slug %}">{{article.title}}</a> </h2>
        <p>{{article.snippat}}</p>
        <p>{{article.date}}</p>
        <p class="author"> added by {{article.author.username}}</p>
      </div>
      {% endfor %}
    </div>
    {% endblock %}

myblog/articles/templates/articles/details.html
{% extends 'base_layout.html'%}
{% block content %}
<div class="article-details">
<div class="article">
  <h1>{{article.title}}</h1>
  <img src="{{article.thumb.url}}" alt="">
  <p>{{article.body}}</p>
  <p>{{article.date}}</p>

</div>
</div>
{% endblock %}

myblog/feedback/templates/feedback/about.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
{% block content %}

	<h1>This Blog Is Developed By:-</h1>
	

		<strong style="font-size: 30px; font-family: 'Gaegu', cursive;">Hello I am Vikas and and i am currently pursuing my bachelors degree in Information Technology at Indian Institute Of Information Technology,Vadodara
	</strong>
	
		<h1>For More Information You can text me here :-</h1>
		<form class="site-form" method="POST" action="{% url 'feedback:about'%}">
			{% csrf_token %}
			{{form}}
			<input type="submit" value="Submit">
		</form>
		
	
	<div class="about">
		<h1>You can also find me on:-</h1>
	<a href="https://github.com/vikassharma1999"><i class="fab fa-github"></i></a>
	<a href="https://www.linkedin.com/in/vikas-sharma-04a11a156/"><i class="fab fa-linkedin-in"></i></a>
	<a href="https://www.facebook.com/profile.php?id=100005685854754"><i class="fab fa-facebook-square"></i></a>
	<a href="https://twitter.com/Vikassh89501557"><i class="fab fa-twitter-square"></i></a>
</div>


{% endblock %}

myblog/feedback/templates/feedback/feed.html
{% extends 'base_layout.html' %}
{% block content %}

<div>
	<h1>Give Your Feedback</h1>
</div>
<form class="site-form" action="{% url 'feedback:feed'%}" method="POST">
	{% csrf_token %}
	{{form}}
	<input type="submit" value="Submit">
</form>

{% endblock %}

myblog/feedback/templates/feedback/thanks.html
{% extends 'base_layout.html' %}
{% block content %}
<h1>Thanks for your feedback</h1>
<hr>
<h3>Here is The List Of some Feedback:-</h3>
{% for x in data %}

<ol>

<strong>{{x.feed_back}}</strong>
</ol>

{% endfor %}
{% endblock %}

myblog/templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>About us:-</h1>
    <p>hello gays</p>
  </body>
</html>

myblog/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Article</title>
    <link href="https://fonts.googleapis.com/css?family=Gaegu" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css'%}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.png'%}" />
  </head>
  <body>

    <header class="wrapper">
<h1><a href="{% url 'home' %}"><i class="fas fa-home"></i></a></h1>
</header>
  <div class="wrapper">

<nav>
  <ul>
    {% if user.is_authenticated%}
    <li>
      <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="highlight">Logout</button>
      </form>
    </li>

    <li><a href="{% url 'feedback:feed' %}" class="highlight">Feedback</a></li>
    <li><a href="{% url 'articles:create'%}" class="highlight">New Article</a></li>
    <li><a href="{% url 'feedback:about'%}" class="highlight">About</a></li>
    {% else %}
    <li><a href="{% url 'accounts:login'%}" class="highlight">Login</a></li>
    <li><a href="{% url 'accounts:signup'%}" class="highlight">Signup</a></li>
   <li><a href="{% url 'feedback:about'%}" class="highlight">About</a></li>

    {% endif %}
  </ul>
</nav>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

myblog/templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
  </head>
  <body>
    <h1>This is my Homepage</h1>
    <p>Welcome to my blog</p>
  </body>
</html>